version: "3.1"
services:

  # nginx frontend app server
  frontend:
    build: frontend
    container_name: "servermanager_frontend"
    ports:
      - 8080:80
    volumes:
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/app/dist:/usr/share/nginx/html

  # test centos server openssh
  test:
    build: test
    container_name: "servermanager_test"
